# Generated by Django 5.2 on 2025-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpaymentmethod',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Payment Method', 'verbose_name_plural': 'Customer Payment Methods'},
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
