# Generated by Django 5.2 on 2025-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficfine',
            name='car',
        ),
    ]
