# Generated by Django 5.2 on 2025-04-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_is_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_extension',
        ),
    ]
