# Generated by Django 5.2 on 2025-05-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_customerpaymentmethod_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpaymentmethod',
            old_name='stripe_payment_intent_id',
            new_name='stripe_setup_intent_id',
        ),
    ]
