# Generated by Django 5.2 on 2025-05-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_stripe_payment_intent_id_customerpaymentmethod_stripe_setup_intent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPaymentMethod',
        ),
    ]
