# Generated by Django 5.2 on 2025-04-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carhotellink_in_car_extension_url_and_more'),
        ('payments', '0003_remove_payment_is_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('initial', 'Initial Payment'), ('extension', 'Extension Payment')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
