# Generated by Django 5.2 on 2025-05-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_trafficfine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficFine',
        ),
    ]
