# Generated by Django 5.2 on 2025-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_trafficfine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
