# Generated by Django 5.2 on 2025-05-07 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Van', 'Van')], default='Sedan', max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cleaning', 'Cleaning'), ('outofservice', 'Out of Service')], default='available', max_length=50)),
                ('price_per_hour', models.FloatField(default=0.0)),
                ('max_price_per_day', models.FloatField(default=0.0)),
                ('passengers', models.PositiveIntegerField(default=4, help_text='Number of passengers the car can accommodate.')),
                ('doors', models.PositiveIntegerField(default=4, help_text='Number of doors on the car.')),
                ('luggage', models.PositiveIntegerField(default=1, help_text='Approximate number of luggage bags the car can fit.')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='Automatic', help_text='Type of transmission.', max_length=10)),
                ('air_conditioning', models.BooleanField(default=True, help_text='Whether the car has air conditioning.')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='Petrol', help_text='Type of fuel the car uses.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('fiscal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_license', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('guest_booking_url', models.URLField(blank=True, help_text='URL encoded in hotel QR code to access car rental booking page', unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='hotel_qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('portal_url', models.URLField(blank=True, help_text="URL for the rental company's admin portal or reference", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('buffer_time', models.IntegerField(default=30)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.car')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='rental_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='api.rentalcompany'),
        ),
        migrations.AddField(
            model_name='car',
            name='rental_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.rentalcompany'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Van', 'Van')], default='Sedan', max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cleaning', 'Cleaning'), ('outofservice', 'Out of Service')], default='available', max_length=50)),
                ('price_per_hour', models.FloatField(default=0.0)),
                ('max_price_per_day', models.FloatField(default=0.0)),
                ('in_car_extension_url', models.URLField(blank=True, help_text='Auto-generated URL for rental extension', null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vehicle_qr_codes/')),
                ('passengers', models.PositiveIntegerField(default=4, help_text='Number of passengers the vehicle can accommodate.')),
                ('doors', models.PositiveIntegerField(default=4, help_text='Number of doors on the vehicle.')),
                ('luggage', models.PositiveIntegerField(default=1, help_text='Approximate number of luggage bags the vehicle can fit.')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='Automatic', help_text='Type of transmission.', max_length=10)),
                ('air_conditioning', models.BooleanField(default=True, help_text='Whether the vehicle has air conditioning.')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='Petrol', help_text='Type of fuel the vehicle uses.', max_length=10)),
                ('hotel', models.ForeignKey(help_text='Hotel where the vehicle is available', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.hotel')),
                ('rental_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.rentalcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CarHotelLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_car_extension_url', models.URLField(blank=True, help_text='Auto-generated URL for rental extension', null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='car_qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_link', to='api.car')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_cars', to='api.hotel')),
            ],
            options={
                'unique_together': {('car', 'hotel')},
            },
        ),
    ]
