# Generated by Django 5.2 on 2025-05-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.DeleteModel(
            name='BookingConflict',
        ),
    ]
