# Generated by Django 5.2 on 2025-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='fiscal_code',
        ),
        migrations.AddField(
            model_name='guest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Località'),
        ),
        migrations.AddField(
            model_name='guest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='guest',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Via'),
        ),
    ]
