# Generated by Django 5.2 on 2025-05-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='driver_license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
