# Generated by Django 5.2 on 2025-05-09 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_booking_status_delete_bookingconflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('conflict', 'Conflict'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('upgraded', 'Upgraded Vehicle')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('affected_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_conflicts', to='api.booking')),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conflicts', to='api.booking')),
            ],
            options={
                'unique_together': {('original_booking', 'affected_booking')},
            },
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
