# Generated by Django 5.2 on 2025-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_guest_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
