# Generated by Django 5.2 on 2025-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_guest_fiscal_code_guest_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('pending_conflict', 'Pending Conflict'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
