# Generated by Django 5.2 on 2025-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='carhotellink',
            name='in_car_extension_url',
            field=models.URLField(blank=True, help_text='Auto-generated URL for rental extension', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carhotellink',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='car_qr_codes/'),
        ),
    ]
