# Generated by Django 5.2 on 2025-05-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
