# Generated by Django 5.2 on 2025-05-03 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_guest_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='driver_license',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
