# Generated by Django 5.2 on 2025-04-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carhotellink_in_car_extension_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
