# Generated by Django 5.2 on 2025-05-09 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_created_at_booking_status_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Van', 'Van')], default='Sedan', max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cleaning', 'Cleaning'), ('outofservice', 'Out of Service')], default='available', max_length=50)),
                ('price_per_hour', models.FloatField(default=0.0)),
                ('max_price_per_day', models.FloatField(default=0.0)),
                ('in_car_extension_url', models.URLField(blank=True, help_text='Auto-generated URL for rental extension', null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vehicle_qr_codes/')),
                ('passengers', models.PositiveIntegerField(default=4, help_text='Number of passengers the vehicle can accommodate.')),
                ('doors', models.PositiveIntegerField(default=4, help_text='Number of doors on the vehicle.')),
                ('luggage', models.PositiveIntegerField(default=1, help_text='Approximate number of luggage bags the vehicle can fit.')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='Automatic', help_text='Type of transmission.', max_length=10)),
                ('air_conditioning', models.BooleanField(default=True, help_text='Whether the vehicle has air conditioning.')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='Petrol', help_text='Type of fuel the vehicle uses.', max_length=10)),
                ('hotel', models.ForeignKey(help_text='Hotel where the vehicle is available', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.hotel')),
                ('rental_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.rentalcompany')),
            ],
        ),
        migrations.DeleteModel(
            name='Conflict',
        ),
    ]
