# Generated by Django 5.2 on 2025-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_created_at_remove_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('pending_conflict', 'Pending Conflict')], default='active', max_length=20),
        ),
    ]
