# Generated by Django 5.2 on 2025-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_guest_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.CharField(null=True),
        ),
    ]
