# Generated by Django 5.2 on 2025-04-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_customer_id',
        ),
    ]
