# Generated by Django 5.2 on 2025-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_amount_booking_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
