# Generated by Django 5.2 on 2025-05-12 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('conflicting_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='api.booking')),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_conflicts', to='api.booking')),
            ],
        ),
    ]
