# Generated by Django 5.2 on 2025-05-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookingconflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingconflict',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
