# Generated by Django 5.2 on 2025-05-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_booking_amount_alter_booking_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reason',
        ),
    ]
