# Generated by Django 5.2 on 2025-04-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_challan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challan',
        ),
    ]
