# Generated by Django 5.2 on 2025-05-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_guest_driver_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='driver_license',
        ),
    ]
