# Generated by Django 5.2 on 2025-05-02 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_guest_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='driver_license',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='drivers_license/'),
            preserve_default=False,
        ),
    ]
