# Generated by Django 5.2 on 2025-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_guest_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='driver_license',
            field=models.CharField(),
        ),
    ]
