# Generated by Django 5.2 on 2025-05-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_guest_driver_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='driver_license',
        ),
    ]
