

"""
Django settings for middleware_platform project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables: .env.prod takes priority, falls back to .env.local
env_prod = BASE_DIR / '.env.prod'
env_local = BASE_DIR / '.env.local'

if env_prod.exists():
    load_dotenv(env_prod)
elif env_local.exists():
    load_dotenv(env_local)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-me')
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

BASE_URL_FRONTEND = os.getenv('BASE_URL_FRONTEND', 'http://localhost:5173')
BASE_URL_BACKEND = os.getenv('BASE_URL_BACKEND', 'http://localhost:8000')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'payments',  # Add your payments app here
    'django_extensions'
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ Dev only. Use whitelist in production.

# CSRF_TRUSTED_ORIGINS = [
#     "https://rental.mdlabs.it",
#     "https://rental.mdlabs.it",
#     "https://www.rental.mdlabs.it",
#     "http://rental.mdlabs.it",
#     "http://www.rental.mdlabs.it",
#     "http://127.0.0.1:8000",
#     "http://localhost:5173",
#     "http://159.223.221.86:5173",
#     "http://159.223.221.86:8000",
#     "http://159.223.221.86",
#     "https://api.mdlabs.it"
#     ]

JAZZMIN_SETTINGS = {
    "site_title": "Rental Platform Admin",
    "site_header": "Rental Dashboard",
    "site_brand": "Rental Car System",
    "welcome_sign": "Welcome to the Rental Management System",

    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    
    
}


    



# Email settings
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')
DEFAULT_FROM_NAME = os.getenv('DEFAULT_FROM_NAME', 'Rental Platform')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', '')
ADMINS = [('Admin', ADMIN_EMAIL)]


EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST           = os.getenv('EMAIL_HOST', 'smtps.aruba.it')
EMAIL_PORT           = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_USE_SSL        = os.getenv('EMAIL_USE_SSL', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER      = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD  = os.getenv('EMAIL_HOST_PASSWORD', '')


# URL for accessing media files in the browser
MEDIA_URL = '/media/'


# Path for storing uploaded media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# settings.py
LOGIN_URL = 'admin:login'            # Redirect to admin login (not accounts/login)
LOGIN_REDIRECT_URL = 'admin:index'   # After login, go to admin dashboard
LOGOUT_REDIRECT_URL = 'admin:login'  # After logout, return to admin login
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'middleware_platform.urls'

TEMPLATES = [
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'middleware_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": os.getenv('DB_ENGINE', 'django.db.backends.postgresql_psycopg2'),
            "NAME": os.getenv('DB_NAME', 'project'),
            "USER": os.getenv('DB_USER', 'postgres'),
            "PASSWORD": os.getenv('DB_PASSWORD', ''),
            "HOST": os.getenv('DB_HOST', 'localhost'),
            "PORT": os.getenv('DB_PORT', '5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic puts files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Your original static files directory
]

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True