"""
Django settings for middleware_platform project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import warnings
warnings.filterwarnings("ignore", message=".*pin_memory.*")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i6khrkioubhlq5x=fqcz0i7y3kowbg3_y-07ard_*5-0h0!_6='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
STRIPE_SECRET_KEY = 'sk_test_51REXBZIpkMgm9AXd3PAkWm1K9cNMftuYBDkoPsnNorDv8hUfldb0XDE1BEoamNzUEMhGSQ22JIUerkOTKYBUyOnw00syRm0uQE'
STRIPE_PUBLIC_KEY = 'pk_test_51REXBZIpkMgm9AXd10Wr8V2dZqE0FgNXyn8ow7KDMr2lLizFHHyKgE5mUab5QBx9zTfb40Kd1vczMZKpb7gdvCTw003jH7RCPY'
STRIPE_WEBHOOK_SECRET = 'whsec_Xj3zKkb5RYiC0eAtz182nHuhP4nKl63Y'
BASE_URL_FRONTEND = "http://localhost:5173"
BASE_URL_BACKEND = "http://127.0.0.1:8000"

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'f4bc-47-53-13-51.ngrok-free.app']



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'payments',  # Add your payments app here
    'django_extensions',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ Dev only. Use whitelist in production.
JAZZMIN_SETTINGS = {
    "site_title": "Rental Platform Admin",
    "site_header": "Rental Dashboard",
    "site_brand": "Rental Car System",
    "welcome_sign": "Welcome to the Rental Management System",

    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    
    
}
# Brevo (Sendinblue) settings
BREVO_API_KEY = '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'
DEFAULT_FROM_EMAIL = 'chatgpt6910@gmail.com'
DEFAULT_FROM_NAME = 'Rental Platform'
ADMIN_EMAIL = 'zeeshan6910@gmail.com'
ADMINS = [('Admin', ADMIN_EMAIL)]

    



# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-relay.brevo.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = '8cfff2001@smtp-brevo.com'  # Your Outlook/Live email address
# EMAIL_HOST_PASSWORD = 'kbNJUOx5F2KMQWYG'  # Your Outlook/Live account password (or app password if 2FA is enabled)
# ADMIN_EMAIL = 'tech@mdacademy.it'


import os

# URL for accessing media files in the browser
MEDIA_URL = '/media/'


# Path for storing uploaded media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# settings.py
LOGIN_URL = 'admin:login'            # Redirect to admin login (not accounts/login)
LOGIN_REDIRECT_URL = 'admin:index'   # After login, go to admin dashboard
LOGOUT_REDIRECT_URL = 'admin:login'  # After logout, return to admin login
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'middleware_platform.urls'

TEMPLATES = [
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'middleware_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'project',  # Your PostgreSQL database name
        'USER': 'postgres',  # Your PostgreSQL user
        'PASSWORD': '221299',  # Your PostgreSQL user's password
        'HOST': 'localhost',  # If PostgreSQL is running locally
        'PORT': '5432',  # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # <-- This line is important
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
